### ISSUE TITLE
--network=host

### ISSUE THREAD

**Issue by MicroLord** [luhuiguo/fastdfs-docker#1]
how to get the container's ip

**Comment by wodog** [comment]
when --network=host, container's ip is host ip

**Comment by rootrl** [comment]
> when --network=host, container's ip is host ip

So we can only use the different port for different storage server, and we can't cross the physical machine(the right way is create the overlay network).

lots of issue with this project.

**Comment by Gred01** [comment]
and windows docker is not supported the network pattern !!!
when the docker of windows used the net=host,the container‘s ip is the vistual linux ip rather than the host ip
